services:
  - type: web
    name: elp-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py  # ← ИЗМЕНИТЕ bot.py на app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
